# Generated by Django 4.2.16 on 2024-11-18 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_loanproducts_loan_lmt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanoptions',
            name='mrtg_type_nm',
            field=models.TextField(default='전세자금대출'),
        ),
    ]
