# Generated by Django 4.2.16 on 2024-11-18 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_loanoptions_mrtg_type_nm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanoptions',
            name='mrtg_type_nm',
            field=models.TextField(blank=True, default='전세자금대출', null=True),
        ),
    ]
