# Generated by Django 4.2.16 on 2024-11-19 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_loanoptions_mrtg_type_nm'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditLoanProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_prdt_cd', models.TextField(unique=True)),
                ('kor_co_nm', models.TextField()),
                ('fin_prdt_nm', models.TextField()),
                ('join_way', models.TextField()),
                ('crdt_prdt_type_nm', models.TextField()),
                ('dcls_strt_day', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CreditLoanOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_prdt_cd', models.TextField()),
                ('crdt_lend_rate_type_nm', models.TextField()),
                ('crdt_grad_1', models.FloatField(null=True)),
                ('crdt_grad_4', models.FloatField(null=True)),
                ('crdt_grad_5', models.FloatField(null=True)),
                ('crdt_grad_6', models.FloatField(null=True)),
                ('crdt_grad_10', models.FloatField(null=True)),
                ('crdt_grad_11', models.FloatField(null=True)),
                ('crdt_grad_12', models.FloatField(null=True)),
                ('crdt_grad_13', models.FloatField(null=True)),
                ('crdt_grad_avg', models.FloatField(null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.loanproducts')),
            ],
        ),
    ]
