# Generated by Django 4.2.16 on 2024-11-19 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_creditloanproducts_creditloanoptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditloanoptions',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.creditloanproducts'),
        ),
    ]
