# Generated by Django 4.2.16 on 2024-11-19 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_creditloanoptions_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditloanproducts',
            name='join_way',
            field=models.TextField(null=True),
        ),
    ]
